{% set version = "0.6.2" %}

package:
  name: docopt
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/d/docopt/docopt-{{ version }}.tar.gz
  sha256: 49b3a825280bd66b3aa83585ef59c4a8c82f2c8a522dbe754a8bc8d08c85c491

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - docopt

about:
  home: http://docopt.org
  license: MIT
  license_file: LICENSE-MIT
  summary: Pythonic argument parser, that will make you smile

extra:
  recipe-maintainers:
    - ocefpaf
