{% set version = "0.6.2" %}

package:
    name: docopt
    version: {{ version }}

source:
    fn: docopt-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/d/docopt/docopt-{{ version }}.tar.gz
    md5: 4bc74561b37fad5d3e7d037f82a4c3b1

build:
  noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - docopt

about:
    home: http://docopt.org
    license: MIT
    summary: Pythonic argument parser, that will make you smile

extra:
    recipe-maintainers:
        - ocefpaf
