travis:
  secure:
    BINSTAR_TOKEN: LNb56mf2OoLGK3sykuq4R3V3oRN0V//9k7YKU6SVbgzFI5xWLrldoOhVpKks1JvVQ45EIzrToKEaooroBcvztcQzSDOBQgppqtDTMJSfJ3fOIq1klipfgPBMsfPM0yfNCoKpenWSMN0v2VJVtbxThN1HWrh4vVLuUxsw/z5sH6F8PbcveqehN1kTzZplHyICFTYRGuEbLRe5WNCC89Nlj497UJ9e0b53ACS+Rx8zkSwWTWi4Hwp5FMNH5GM3D7SOeDV4Ma3zTDMCtNi5l7TCgYCKjw2rc1VIby07tSRfts8jYOIc+qYiaEoVVRN2tulbctQWBOdAeW4trVYNFNRW7QVfxcmLGSascKMO5cUj1gfMTmCiwq9UWNRuYz11UZJB700okBP6qHl5VizGvb11M+6cM2B1wA8pof1/9jfklDcAXIN07MWeRet1SjP94nLVgkdIG8z7yYVx7WOqd8+bBGslg+L9PcKhCNdlOyz5lj/cT1dBe3LyESQuurf28KQtDM7Rr8EBRCCmPQ8+nk9KTXqqBmLJ79eCJ0JqJ38S9wIlX1DqrUVpjMpDEEnrwKW7EWNJAxd5zR9ORVuhbhmU3K5EizL7hgTKvZ2AMVpJ7HWOtRNzDfSK8cqCBXQ2MV+Mi7I7mtgfMd57YJGDbwwL4nhDxv3A/ePJvvi3cozWYcY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
